language:
  - cpp
os:
  - linux
compiler:
  - gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y qt5-qmake
script:
  - mkdir build && cd build
  - qmake ../breeze_flight_control_station.pro
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - myyerrol@126.com
    on_success: change
    on_failure: always
