language:
  - cpp
os:
  - linux
compiler:
  - gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y qtbase5-dev libqt5multimedia5 libqt5multimediawidgets5 libqt5serialport5
script:
  - mkdir build && cd build
  - qmake ../breeze_flight_control_station.pro && make
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - myyerrol@126.com
    on_success: change
    on_failure: always
